FROM node:8.11.3-slim as node

ENV NODE_VERSION 8.11.3
ENV YARN_VERSION 1.6.0

FROM ruby:<%= tag %>

COPY --from=node /usr/local/bin/node /usr/local/bin/node
RUN ln -s /usr/local/bin/node /usr/local/bin/nodejs
COPY --from=node /usr/local/bin/yarn /usr/local/bin/yarn
COPY --from=node /usr/local/bin/yarnpkg /usr/local/bin/yarnpkg
