FROM node:8.11.3-slim as node

ENV NODE_VERSION 8.11.3
ENV YARN_VERSION 1.6.0

FROM ruby:<%= tag %>

COPY --from=node /usr/local/bin/ /usr/local/bin/
COPY --from=node /usr/local/lib/ /usr/local/lib/
COPY --from=node /opt/yarn-v1.6.0/ /opt/yarn-v1.6.0/
